# bash_profile

sourcefiles=(
    ~/.mydotfiles/bash/exports
    ~/.mydotfiles/bash/aliases
    ~/.mydotfiles/bash/bash_prompt
    ~/.mydotfiles/git/git-autocompletion.sh
    ~/.mydotfiles/npm/npm-completion.sh
)

for file in ${sourcefiles[@]}; do
    source $file
done

# neverending bash history
shopt -s histappend


# set default file permissions
umask 002

# nvm (orginally placed in .bashrc / moved here manually
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*


# sudo gem install travis
# added by travis gem in bashrc
#[ -f /Users/yungjames/.travis/travis.sh ] && source /Users/yungjames/.travis/travis.sh
[ -f ${HOME}/.travis/travis.sh ] && source ${HOME}/.travis/travis.sh



#export PATH=$HOME/dev/go-lang/bin:$PATH
#export PATH=$PATH:/usr/local/gnupg-2.1/bin
#export GOPATH=$HOME/dev/go-lang/
