# bash_profile

sourcefiles=(
	~/.mydotfiles/bash/exports
	~/.mydotfiles/bash/aliases
	~/.mydotfiles/bash/bash_prompt
	~/.mydotfiles/git/git-autocompletion.sh
)

for file in ${sourcefiles[@]}; do
	source $file
done

# neverending bash history
shopt -s histappend


# set default file permissions
umask 002
